#!/usr/bin/env bash

set -e

if [ ! -f start ]; then
    echo 'start must be run within its container folder' 1>&2
    exit 1
fi

bin/sgl >> log/panic.log 2>&1 &

echo "start successfully"
tail -f log/panic.log